# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: butter.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='butter.proto',
  package='ButterStream',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x62utter.proto\x12\x0c\x42utterStream\"2\n\x0bSessionInfo\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"<\n\nConnectArg\x12.\n\x0bsessionInfo\x18\x01 \x01(\x0b\x32\x19.ButterStream.SessionInfo\"?\n\rDisconnectArg\x12.\n\x0bsessionInfo\x18\x01 \x01(\x0b\x32\x19.ButterStream.SessionInfo\"@\n\x0eStartStreamArg\x12.\n\x0bsessionInfo\x18\x01 \x01(\x0b\x32\x19.ButterStream.SessionInfo\"?\n\rStopStreamArg\x12.\n\x0bsessionInfo\x18\x01 \x01(\x0b\x32\x19.ButterStream.SessionInfo\"+\n\x0cReturnStatus\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\"\x1c\n\rDataContainer\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x32\xa8\x02\n\x0bVideoStream\x12?\n\x07\x63onnect\x12\x18.ButterStream.ConnectArg\x1a\x1a.ButterStream.ReturnStatus\x12J\n\x0bstartStream\x12\x1c.ButterStream.StartStreamArg\x1a\x1b.ButterStream.DataContainer0\x01\x12\x45\n\nstopStream\x12\x1b.ButterStream.StopStreamArg\x1a\x1a.ButterStream.ReturnStatus\x12\x45\n\ndisconnect\x12\x1b.ButterStream.DisconnectArg\x1a\x1a.ButterStream.ReturnStatusb\x06proto3'
)




_SESSIONINFO = _descriptor.Descriptor(
  name='SessionInfo',
  full_name='ButterStream.SessionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='ButterStream.SessionInfo.clientId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ButterStream.SessionInfo.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=80,
)


_CONNECTARG = _descriptor.Descriptor(
  name='ConnectArg',
  full_name='ButterStream.ConnectArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionInfo', full_name='ButterStream.ConnectArg.sessionInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=142,
)


_DISCONNECTARG = _descriptor.Descriptor(
  name='DisconnectArg',
  full_name='ButterStream.DisconnectArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionInfo', full_name='ButterStream.DisconnectArg.sessionInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=207,
)


_STARTSTREAMARG = _descriptor.Descriptor(
  name='StartStreamArg',
  full_name='ButterStream.StartStreamArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionInfo', full_name='ButterStream.StartStreamArg.sessionInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=273,
)


_STOPSTREAMARG = _descriptor.Descriptor(
  name='StopStreamArg',
  full_name='ButterStream.StopStreamArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionInfo', full_name='ButterStream.StopStreamArg.sessionInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=338,
)


_RETURNSTATUS = _descriptor.Descriptor(
  name='ReturnStatus',
  full_name='ButterStream.ReturnStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ButterStream.ReturnStatus.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='ButterStream.ReturnStatus.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=383,
)


_DATACONTAINER = _descriptor.Descriptor(
  name='DataContainer',
  full_name='ButterStream.DataContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='ButterStream.DataContainer.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=413,
)

_CONNECTARG.fields_by_name['sessionInfo'].message_type = _SESSIONINFO
_DISCONNECTARG.fields_by_name['sessionInfo'].message_type = _SESSIONINFO
_STARTSTREAMARG.fields_by_name['sessionInfo'].message_type = _SESSIONINFO
_STOPSTREAMARG.fields_by_name['sessionInfo'].message_type = _SESSIONINFO
DESCRIPTOR.message_types_by_name['SessionInfo'] = _SESSIONINFO
DESCRIPTOR.message_types_by_name['ConnectArg'] = _CONNECTARG
DESCRIPTOR.message_types_by_name['DisconnectArg'] = _DISCONNECTARG
DESCRIPTOR.message_types_by_name['StartStreamArg'] = _STARTSTREAMARG
DESCRIPTOR.message_types_by_name['StopStreamArg'] = _STOPSTREAMARG
DESCRIPTOR.message_types_by_name['ReturnStatus'] = _RETURNSTATUS
DESCRIPTOR.message_types_by_name['DataContainer'] = _DATACONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionInfo = _reflection.GeneratedProtocolMessageType('SessionInfo', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONINFO,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.SessionInfo)
  })
_sym_db.RegisterMessage(SessionInfo)

ConnectArg = _reflection.GeneratedProtocolMessageType('ConnectArg', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTARG,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.ConnectArg)
  })
_sym_db.RegisterMessage(ConnectArg)

DisconnectArg = _reflection.GeneratedProtocolMessageType('DisconnectArg', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTARG,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.DisconnectArg)
  })
_sym_db.RegisterMessage(DisconnectArg)

StartStreamArg = _reflection.GeneratedProtocolMessageType('StartStreamArg', (_message.Message,), {
  'DESCRIPTOR' : _STARTSTREAMARG,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.StartStreamArg)
  })
_sym_db.RegisterMessage(StartStreamArg)

StopStreamArg = _reflection.GeneratedProtocolMessageType('StopStreamArg', (_message.Message,), {
  'DESCRIPTOR' : _STOPSTREAMARG,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.StopStreamArg)
  })
_sym_db.RegisterMessage(StopStreamArg)

ReturnStatus = _reflection.GeneratedProtocolMessageType('ReturnStatus', (_message.Message,), {
  'DESCRIPTOR' : _RETURNSTATUS,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.ReturnStatus)
  })
_sym_db.RegisterMessage(ReturnStatus)

DataContainer = _reflection.GeneratedProtocolMessageType('DataContainer', (_message.Message,), {
  'DESCRIPTOR' : _DATACONTAINER,
  '__module__' : 'butter_pb2'
  # @@protoc_insertion_point(class_scope:ButterStream.DataContainer)
  })
_sym_db.RegisterMessage(DataContainer)



_VIDEOSTREAM = _descriptor.ServiceDescriptor(
  name='VideoStream',
  full_name='ButterStream.VideoStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=416,
  serialized_end=712,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect',
    full_name='ButterStream.VideoStream.connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTARG,
    output_type=_RETURNSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startStream',
    full_name='ButterStream.VideoStream.startStream',
    index=1,
    containing_service=None,
    input_type=_STARTSTREAMARG,
    output_type=_DATACONTAINER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopStream',
    full_name='ButterStream.VideoStream.stopStream',
    index=2,
    containing_service=None,
    input_type=_STOPSTREAMARG,
    output_type=_RETURNSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='disconnect',
    full_name='ButterStream.VideoStream.disconnect',
    index=3,
    containing_service=None,
    input_type=_DISCONNECTARG,
    output_type=_RETURNSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIDEOSTREAM)

DESCRIPTOR.services_by_name['VideoStream'] = _VIDEOSTREAM

# @@protoc_insertion_point(module_scope)
